name: flutter_statusbarcolor
description: A package can help you to change your flutter app's statusbar's color or navigationbar's color programmatically.
version: 0.2.4
author: "fuyumi <fnatic.roach@gmail.com>"
homepage: https://github.com/cat-x/flutter_statusbarcolor

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.fuyumi.flutterstatusbarcolor.flutterstatusbarcolor
        pluginClass: FlutterStatusbarcolorPlugin
      ios:
        pluginClass: FlutterStatusbarcolorPlugin
